### ISSUE TITLE
Script only runs from the diagnostics-01 folder

### ISSUE THREAD

**Issue by jcbmiller94** [psych-214-fall-2016/diagnostics-01#23]
Small note, but when I tried to run the find_outliers.py script from a directory that was no 'diagnostics-01' (i.e. by calling it as scripts/find_outlier.py) the script did not run. 

However, it works great otherwise! The data path can still be specified from wherever

**Comment by jdtheiss** [comment]
The newest update improves the find_outliers script so that it can be called from any directory.
